- hosts: localhost
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        update_cache: true
      tags:
        - zsh
        - neovim
        - docker
    - name: Install curl
      become: true
      apt: name=curl
      tags:
        - zsh
        - neovim
        - docker
  tasks:
    - include: tasks/zsh.yml
    - include: tasks/neovim.yml
    - include: tasks/docker.yml
