- hosts: localhost
  pre_tasks:
    - name: Update cache and install basic deps
      become: true
      apt:
        update_cache: true
        name: ["curl", "make"]
      tags:
        - zsh
        - neovim
        - docker
        - node
  tasks:
    - include: tasks/zsh.yml
    - include: tasks/neovim.yml
    - include: tasks/docker.yml
    - include: tasks/nodejs.yml
