- name: Get brave keyring
  become: true
  shell: curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
  tags:
    - brave
- name: Add brave to repo list
  shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
  tags:
    - brave
- name: Update cache
  become: true
  apt:
    update_cache: yes
  tags:
    - brave
- name: Install brave
  become: true
  apt:
    name: brave-browser
  tags:
    - brave
