- name: Install docker requiremnets
  become: true
  apt:
    name: ["ca-certificates", "gnupg", "lsb-release"]
  tags:
    - docker
- name: Add docker gpg key
  become: true
  shell: mkdir -p /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  tags:
    - docker
- name: Set up docker repo
  become: true
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  tags:
    - docker
- name: Install docker
  become: true
  apt:
    update_cache: true
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-compose-plugin"]
  tags:
    - docker
- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present
  tags:
    - docker
  ignore_errors: yes
- name: Add user to docker group
  become: true
  ansible.builtin.user:
    user: "{{ ansible_user_id }}"
    append: true
    groups: ['docker']
