- name: Install docker requiremnets
  apt:
    name: ["ca-certificates", "gnupg", "lsb-release"]
  tags:
    - docker
- name: Add docker gpg key
  shell: mkdir -p /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  tags:
    - docker
- name: Set up docker repo
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  tags:
    - docker
- name: Install docker
  apt:
    update_cache: true
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-compose-plugin"]
  tags:
    - docker
- name: Create docker group
  shell: groupadd docker
  tags:
    - docker
  igonore_errors: yes
- name: Add user to docker group
  shell: usermod -aG docker {{user}}
