- name: Install zsh
  become: true
  apt: name=zsh
  tags:
    - zsh
- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags:
    - zsh
- name: Change shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  tags:
    - zsh
