- name: Install zsh
  apt: name=zsh
  tags:
    - zsh
- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  become_user: {{user}}
  tags:
    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags:
    - zsh
- name: Change shell
  shell: chsh -s `which zsh`
  become_user: {{user}}
  tags:
    - zsh
